"""Initial migration

Revision ID: 8c0424206618
Revises: 
Create Date: 2025-06-03 01:30:06.873252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0424206618'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_symbols',
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.Column('Company Name', sa.Text(), nullable=True),
    sa.Column('Industry', sa.Text(), nullable=True),
    sa.Column('Symbol', sa.String(length=10), nullable=False),
    sa.Column('Series', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('isin'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('historical_data_1d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=True),
    sa.Column('close_price', sa.Numeric(), nullable=True),
    sa.Column('high_price', sa.Numeric(), nullable=True),
    sa.Column('low_price', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_symbols.isin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_data_1d')
    op.drop_table('stock_symbols')
    # ### end Alembic commands ###
